### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by Wulfklaue** [Pure-D/workspace-d#56] opened 2016-12-07 12:19 UTC
Trying to compile dscanner ( with DMD 2.072.1 ) using workspace-d shows the following errors:
 
>dmd` src\astprinter.d src\ctags.d src\dscanner_version.d src\etags.d src\highlighter.d src\imports.d src\main.d src\outliner.d src\readers.d src\stats.d src\symbol_finder.d   libdparse\src\dparse\ast.d libdparse\src\dparse\entities.d libdparse\src\dparse\formatter.d libdparse\src\dparse\lexer.d libdparse\src\dparse\parser.d libdparse\src\dparse\rollback_allocator.d libdparse\src\dparse\stack_buffer.d libdparse\src\std\experimental\lexer.d  src\analysis\alias_syntax_check.d src\analysis\asm_style.d src\analysis\auto_function.d src\analysis\auto_ref_assignment.d src\analysis\base.d src\analysis\builtin_property_names.d src\analysis\comma_expression.d src\analysis\config.d src\analysis\constructors.d src\analysis\del.d src\analysis\duplicate_attribute.d src\analysis\enumarrayliteral.d src\analysis\fish.d src\analysis\function_attributes.d src\analysis\helpers.d src\analysis\ifelsesame.d src\analysis\if_statements.d src\analysis\incorrect_infinite_range.d src\analysis\label_var_same_name_check.d src\analysis\lambda_return_check.d src\analysis\length_subtraction.d src\analysis\line_length.d src\analysis\local_imports.d src\analysis\logic_precedence.d src\analysis\mismatched_args.d src\analysis\numbers.d src\analysis\objectconst.d src\analysis\opequals_without_tohash.d src\analysis\package.d src\analysis\pokemon.d src\analysis\range.d src\analysis\redundant_parens.d src\analysis\run.d src\analysis\static_if_else.d src\analysis\stats_collector.d src\analysis\style.d src\analysis\undocumented.d src\analysis\unmodified.d src\analysis\unused.d src\analysis\unused_label.d src\analysis\useless_assert.d  inifiled\source\inifiled.d  dsymbol\src\dsymbol\cache_entry.d dsymbol\src\dsymbol\deferred.d dsymbol\src\dsymbol\import_.d dsymbol\src\dsymbol\modulecache.d dsymbol\src\dsymbol\scope_.d dsymbol\src\dsymbol\semantic.d dsymbol\src\dsymbol\string_interning.d dsymbol\src\dsymbol\symbol.d dsymbol\src\dsymbol\type_lookup.d dsymbol\src\dsymbol\builtin\names.d dsymbol\src\dsymbol\builtin\symbols.d dsymbol\src\dsymbol\conversion\first.d dsymbol\src\dsymbol\conversion\package.d dsymbol\src\dsymbol\conversion\second.d  containers\src\containers\cyclicbuffer.d containers\src\containers\dynamicarray.d containers\src\containers\hashmap.d containers\src\containers\hashset.d containers\src\containers\immutablehashset.d containers\src\containers\openhashset.d containers\src\containers\package.d containers\src\containers\simdset.d containers\src\containers\slist.d containers\src\containers\treemap.d containers\src\containers\ttree.d containers\src\containers\unrolledlist.d containers\src\containers\internal\backwards.d containers\src\containers\internal\element_type.d containers\src\containers\internal\hash.d containers\src\containers\internal\mixins.d containers\src\containers\internal\node.d containers\src\containers\internal\storage_type.d -O -release -inline -I"libdparse\src" -I"dsymbol\src" -I"containers\src" -ofdscanner.exe 
> 
> dsymbol\src\dsymbol\symbol.d(208): Deprecation: this.name.data.ptr cannot be used in @safe code, use &this.name.data[0] instead
> dsymbol\src\dsymbol\symbol.d(208): Deprecation: other.name.data.ptr cannot be used in @safe code, use &other.name.data[0] instead
> dsymbol\src\dsymbol\symbol.d(209): Deprecation: this.name.data.ptr cannot be used in @safe code, use &this.name.data[0] instead
> dsymbol\src\dsymbol\symbol.d(209): Deprecation: other.name.data.ptr cannot be used in @safe code, use &other.name.data[0] instead
> dsymbol\src\dsymbol\symbol.d(216): Deprecation: other.name.data.ptr cannot be used in @safe code, use &other.name.data[0] instead
> dsymbol\src\dsymbol\symbol.d(216): Deprecation: this.name.data.ptr cannot be used in @safe code, use &this.name.data[0] instead
> dsymbol\src\dsymbol\symbol.d(221): Deprecation: this.name.data.ptr cannot be used in @safe code, use &this.name.data[0] instead

And it blocks compilation at this point. Not sure if this needs to be posted here or on the dscanner git. Looks like more of a DMD regression bug to me...

Side issue: Is it normal that workspace-d needs administration rights to properly function / compile ( DCD, DScanner, DFMT )?

**Comment by WebFreak001** [comment] 2016-12-07 16:24
Hm seems like a dscanner issue, try manually running the build.bat file in dscanner (git clone) to be sure. Also it shouldn't need administration rights, I renamed the standalone installer to `iworkspaced` so windows doesn't think it needs them a long time ago.

**Comment by WebFreak001** [comment] 2017-01-06 20:15
can't reproduce on any system, should be fixed if you pull the latest workspace-d release

**Closed as completed by WebFreak001** 2017-01-06 20:15 UTC
Labels: bug, Installer
